theme: jekyll-theme-cayman
title: On the Characterization of Expressive Performance in Classical Music: First Results of the *Con Espressione* Game
description : Experiments for first results of the Con Espressione Game analysis, accepted for ISMIR 2020